version: '3.2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:2.4
    ports:
      - 9200:9200
  redis:
    container_name: redis
    image: redis:3.2
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres:9.6.4
    ports:
      - 5432:5432
